# ==========================================
# TradingASR AI Pro
# File : dynamic_watchlist.py
# Static F&O Watchlist
# ==========================================

def get_watchlist():
    return [
        "RELIANCE.NS",
        "HDFCBANK.NS",
        "ICICIBANK.NS",
        "SBIN.NS",
        "TCS.NS",
        "INFY.NS",
        "HCLTECH.NS",
        "LT.NS",
        "BHARTIARTL.NS",
        "AXISBANK.NS",
        "KOTAKBANK.NS",
        "ASIANPAINT.NS",
        "MARUTI.NS",
        "ULTRACEMCO.NS",
        "SUNPHARMA.NS",
        "BAJFINANCE.NS",
        "BAJAJFINSV.NS",
        "TITAN.NS",
        "NTPC.NS",
        "POWERGRID.NS",
        "ONGC.NS",
        "COALINDIA.NS",
        "ADANIPORTS.NS",
        "ADANIENT.NS",
        "HINDALCO.NS",
        "TATASTEEL.NS",
        "JSWSTEEL.NS",
        "GRASIM.NS",
        "EICHERMOT.NS",
        "HEROMOTOCO.NS",
        "CIPLA.NS",
        "DRREDDY.NS",
        "APOLLOHOSP.NS",
        "TECHM.NS",
        "WIPRO.NS",
        "INDUSINDBK.NS",
        "BEL.NS",
        "HAL.NS",
        "IRFC.NS",
        "RVNL.NS",
        "DLF.NS",
        "LODHA.NS",
        "GAIL.NS",
        "BPCL.NS",
        "IOC.NS",
        "CANBK.NS",
        "PNB.NS",
        "BANKBARODA.NS",
        "SAIL.NS",
        "NMDC.NS",
        "ABB.NS",
        "SIEMENS.NS",
        "BHEL.NS",
        "TORNTPHARM.NS",
        "M&M.NS",
        "TATAPOWER.NS",
        "PFC.NS",
        "RECLTD.NS",
        "INDIGO.NS",
    ]
    
